/*
 * generated by Xtext 2.16.0
 */
package in.handyman.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import in.handyman.ide.contentassist.antlr.internal.InternalDslParser;
import in.handyman.services.DslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getOperatorAccess().getAlternatives(), "rule__Operator__Alternatives");
			builder.put(grammarAccess.getProcessAccess().getGroup(), "rule__Process__Group__0");
			builder.put(grammarAccess.getTryAccess().getGroup(), "rule__Try__Group__0");
			builder.put(grammarAccess.getFinallyAccess().getGroup(), "rule__Finally__Group__0");
			builder.put(grammarAccess.getCatchAccess().getGroup(), "rule__Catch__Group__0");
			builder.put(grammarAccess.getRestPartAccess().getGroup(), "rule__RestPart__Group__0");
			builder.put(grammarAccess.getSendEMailAccess().getGroup(), "rule__SendEMail__Group__0");
			builder.put(grammarAccess.getDeleteFolderAccess().getGroup(), "rule__DeleteFolder__Group__0");
			builder.put(grammarAccess.getTerminalAccess().getGroup(), "rule__Terminal__Group__0");
			builder.put(grammarAccess.getExecJavaAccess().getGroup(), "rule__ExecJava__Group__0");
			builder.put(grammarAccess.getAbortAccess().getGroup(), "rule__Abort__Group__0");
			builder.put(grammarAccess.getDropfileAccess().getGroup(), "rule__Dropfile__Group__0");
			builder.put(grammarAccess.getDoozleAccess().getGroup(), "rule__Doozle__Group__0");
			builder.put(grammarAccess.getFetchAccess().getGroup(), "rule__Fetch__Group__0");
			builder.put(grammarAccess.getCallprocessAccess().getGroup(), "rule__Callprocess__Group__0");
			builder.put(grammarAccess.getForkprocessAccess().getGroup(), "rule__Forkprocess__Group__0");
			builder.put(grammarAccess.getCopydataAccess().getGroup(), "rule__Copydata__Group__0");
			builder.put(grammarAccess.getWriteCsvAccess().getGroup(), "rule__WriteCsv__Group__0");
			builder.put(grammarAccess.getLoadCsvAccess().getGroup(), "rule__LoadCsv__Group__0");
			builder.put(grammarAccess.getTransformAccess().getGroup(), "rule__Transform__Group__0");
			builder.put(grammarAccess.getMongo2DbAccess().getGroup(), "rule__Mongo2Db__Group__0");
			builder.put(grammarAccess.getFTPAccess().getGroup(), "rule__FTP__Group__0");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getGroup(), "rule__RandForestRegressModelTraining__Group__0");
			builder.put(grammarAccess.getRandForestRegressModelTestingAccess().getGroup(), "rule__RandForestRegressModelTesting__Group__0");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getGroup(), "rule__RandForestRegressModelEvaluation__Group__0");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getGroup(), "rule__RandForestClassifyModelTraining__Group__0");
			builder.put(grammarAccess.getRandForestClassifyModelTestingAccess().getGroup(), "rule__RandForestClassifyModelTesting__Group__0");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getGroup(), "rule__RandForestClassifyModelEvaluation__Group__0");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getGroup(), "rule__GradBoostRegressModelTraining__Group__0");
			builder.put(grammarAccess.getGradBoostRegressModelTestingAccess().getGroup(), "rule__GradBoostRegressModelTesting__Group__0");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getGroup(), "rule__GradBoostRegressModelEvaluation__Group__0");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getGroup(), "rule__GradBoostClassifyModelTraining__Group__0");
			builder.put(grammarAccess.getGradBoostClassifyModelTestingAccess().getGroup(), "rule__GradBoostClassifyModelTesting__Group__0");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getGroup(), "rule__GradBoostClassifyModelEvaluation__Group__0");
			builder.put(grammarAccess.getZipAccess().getGroup(), "rule__Zip__Group__0");
			builder.put(grammarAccess.getUnzipAccess().getGroup(), "rule__Unzip__Group__0");
			builder.put(grammarAccess.getChecksumAccess().getGroup(), "rule__Checksum__Group__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
			builder.put(grammarAccess.getProcessAccess().getNameAssignment_1(), "rule__Process__NameAssignment_1");
			builder.put(grammarAccess.getProcessAccess().getTryAssignment_3(), "rule__Process__TryAssignment_3");
			builder.put(grammarAccess.getProcessAccess().getCatchAssignment_4(), "rule__Process__CatchAssignment_4");
			builder.put(grammarAccess.getProcessAccess().getFinallyAssignment_5(), "rule__Process__FinallyAssignment_5");
			builder.put(grammarAccess.getTryAccess().getActionAssignment_2(), "rule__Try__ActionAssignment_2");
			builder.put(grammarAccess.getFinallyAccess().getActionAssignment_2(), "rule__Finally__ActionAssignment_2");
			builder.put(grammarAccess.getCatchAccess().getActionAssignment_2(), "rule__Catch__ActionAssignment_2");
			builder.put(grammarAccess.getRestPartAccess().getPartNameAssignment_2(), "rule__RestPart__PartNameAssignment_2");
			builder.put(grammarAccess.getRestPartAccess().getPartDataAssignment_4(), "rule__RestPart__PartDataAssignment_4");
			builder.put(grammarAccess.getSendEMailAccess().getNameAssignment_2(), "rule__SendEMail__NameAssignment_2");
			builder.put(grammarAccess.getSendEMailAccess().getSourceAssignment_4(), "rule__SendEMail__SourceAssignment_4");
			builder.put(grammarAccess.getSendEMailAccess().getSmtphostAssignment_6(), "rule__SendEMail__SmtphostAssignment_6");
			builder.put(grammarAccess.getSendEMailAccess().getSmtpportAssignment_8(), "rule__SendEMail__SmtpportAssignment_8");
			builder.put(grammarAccess.getSendEMailAccess().getFromAssignment_10(), "rule__SendEMail__FromAssignment_10");
			builder.put(grammarAccess.getSendEMailAccess().getPassAssignment_12(), "rule__SendEMail__PassAssignment_12");
			builder.put(grammarAccess.getSendEMailAccess().getToAssignment_14(), "rule__SendEMail__ToAssignment_14");
			builder.put(grammarAccess.getSendEMailAccess().getCcAssignment_16(), "rule__SendEMail__CcAssignment_16");
			builder.put(grammarAccess.getSendEMailAccess().getBccAssignment_18(), "rule__SendEMail__BccAssignment_18");
			builder.put(grammarAccess.getSendEMailAccess().getSubjectAssignment_20(), "rule__SendEMail__SubjectAssignment_20");
			builder.put(grammarAccess.getSendEMailAccess().getBodyAssignment_22(), "rule__SendEMail__BodyAssignment_22");
			builder.put(grammarAccess.getSendEMailAccess().getSignatureAssignment_24(), "rule__SendEMail__SignatureAssignment_24");
			builder.put(grammarAccess.getSendEMailAccess().getValueAssignment_27(), "rule__SendEMail__ValueAssignment_27");
			builder.put(grammarAccess.getSendEMailAccess().getConditionAssignment_30(), "rule__SendEMail__ConditionAssignment_30");
			builder.put(grammarAccess.getDeleteFolderAccess().getNameAssignment_2(), "rule__DeleteFolder__NameAssignment_2");
			builder.put(grammarAccess.getDeleteFolderAccess().getFoldersourceAssignment_4(), "rule__DeleteFolder__FoldersourceAssignment_4");
			builder.put(grammarAccess.getDeleteFolderAccess().getZipsourceAssignment_6(), "rule__DeleteFolder__ZipsourceAssignment_6");
			builder.put(grammarAccess.getDeleteFolderAccess().getValueAssignment_8(), "rule__DeleteFolder__ValueAssignment_8");
			builder.put(grammarAccess.getDeleteFolderAccess().getConditionAssignment_11(), "rule__DeleteFolder__ConditionAssignment_11");
			builder.put(grammarAccess.getTerminalAccess().getNameAssignment_2(), "rule__Terminal__NameAssignment_2");
			builder.put(grammarAccess.getTerminalAccess().getIdAssignment_4(), "rule__Terminal__IdAssignment_4");
			builder.put(grammarAccess.getTerminalAccess().getValueAssignment_7(), "rule__Terminal__ValueAssignment_7");
			builder.put(grammarAccess.getTerminalAccess().getConditionAssignment_10(), "rule__Terminal__ConditionAssignment_10");
			builder.put(grammarAccess.getExecJavaAccess().getNameAssignment_2(), "rule__ExecJava__NameAssignment_2");
			builder.put(grammarAccess.getExecJavaAccess().getClassFqnAssignment_4(), "rule__ExecJava__ClassFqnAssignment_4");
			builder.put(grammarAccess.getExecJavaAccess().getDbSrcAssignment_6(), "rule__ExecJava__DbSrcAssignment_6");
			builder.put(grammarAccess.getExecJavaAccess().getValueAssignment_8(), "rule__ExecJava__ValueAssignment_8");
			builder.put(grammarAccess.getExecJavaAccess().getConditionAssignment_11(), "rule__ExecJava__ConditionAssignment_11");
			builder.put(grammarAccess.getAbortAccess().getNameAssignment_2(), "rule__Abort__NameAssignment_2");
			builder.put(grammarAccess.getAbortAccess().getValueAssignment_4(), "rule__Abort__ValueAssignment_4");
			builder.put(grammarAccess.getAbortAccess().getConditionAssignment_7(), "rule__Abort__ConditionAssignment_7");
			builder.put(grammarAccess.getDropfileAccess().getNameAssignment_2(), "rule__Dropfile__NameAssignment_2");
			builder.put(grammarAccess.getDropfileAccess().getTargetAssignment_4(), "rule__Dropfile__TargetAssignment_4");
			builder.put(grammarAccess.getDropfileAccess().getConditionAssignment_6(), "rule__Dropfile__ConditionAssignment_6");
			builder.put(grammarAccess.getDoozleAccess().getNameAssignment_2(), "rule__Doozle__NameAssignment_2");
			builder.put(grammarAccess.getDoozleAccess().getTargetAssignment_4(), "rule__Doozle__TargetAssignment_4");
			builder.put(grammarAccess.getDoozleAccess().getOnAssignment_6(), "rule__Doozle__OnAssignment_6");
			builder.put(grammarAccess.getDoozleAccess().getValueAssignment_9(), "rule__Doozle__ValueAssignment_9");
			builder.put(grammarAccess.getDoozleAccess().getConditionAssignment_12(), "rule__Doozle__ConditionAssignment_12");
			builder.put(grammarAccess.getFetchAccess().getNameAssignment_2(), "rule__Fetch__NameAssignment_2");
			builder.put(grammarAccess.getFetchAccess().getSourceAssignment_4(), "rule__Fetch__SourceAssignment_4");
			builder.put(grammarAccess.getFetchAccess().getValueAssignment_7(), "rule__Fetch__ValueAssignment_7");
			builder.put(grammarAccess.getFetchAccess().getConditionAssignment_10(), "rule__Fetch__ConditionAssignment_10");
			builder.put(grammarAccess.getCallprocessAccess().getNameAssignment_2(), "rule__Callprocess__NameAssignment_2");
			builder.put(grammarAccess.getCallprocessAccess().getTargetAssignment_4(), "rule__Callprocess__TargetAssignment_4");
			builder.put(grammarAccess.getCallprocessAccess().getSourceAssignment_6(), "rule__Callprocess__SourceAssignment_6");
			builder.put(grammarAccess.getCallprocessAccess().getDatasourceAssignment_8(), "rule__Callprocess__DatasourceAssignment_8");
			builder.put(grammarAccess.getCallprocessAccess().getValueAssignment_11(), "rule__Callprocess__ValueAssignment_11");
			builder.put(grammarAccess.getCallprocessAccess().getConditionAssignment_14(), "rule__Callprocess__ConditionAssignment_14");
			builder.put(grammarAccess.getForkprocessAccess().getNameAssignment_2(), "rule__Forkprocess__NameAssignment_2");
			builder.put(grammarAccess.getForkprocessAccess().getTargetAssignment_4(), "rule__Forkprocess__TargetAssignment_4");
			builder.put(grammarAccess.getForkprocessAccess().getSourceAssignment_6(), "rule__Forkprocess__SourceAssignment_6");
			builder.put(grammarAccess.getForkprocessAccess().getDatasourceAssignment_8(), "rule__Forkprocess__DatasourceAssignment_8");
			builder.put(grammarAccess.getForkprocessAccess().getValueAssignment_11(), "rule__Forkprocess__ValueAssignment_11");
			builder.put(grammarAccess.getForkprocessAccess().getForkBatchSizeAssignment_14(), "rule__Forkprocess__ForkBatchSizeAssignment_14");
			builder.put(grammarAccess.getForkprocessAccess().getConditionAssignment_16(), "rule__Forkprocess__ConditionAssignment_16");
			builder.put(grammarAccess.getCopydataAccess().getNameAssignment_2(), "rule__Copydata__NameAssignment_2");
			builder.put(grammarAccess.getCopydataAccess().getSourceAssignment_4(), "rule__Copydata__SourceAssignment_4");
			builder.put(grammarAccess.getCopydataAccess().getToAssignment_6(), "rule__Copydata__ToAssignment_6");
			builder.put(grammarAccess.getCopydataAccess().getLimitAssignment_8(), "rule__Copydata__LimitAssignment_8");
			builder.put(grammarAccess.getCopydataAccess().getValueAssignment_11(), "rule__Copydata__ValueAssignment_11");
			builder.put(grammarAccess.getCopydataAccess().getWriteThreadCountAssignment_14(), "rule__Copydata__WriteThreadCountAssignment_14");
			builder.put(grammarAccess.getCopydataAccess().getFetchBatchSizeAssignment_16(), "rule__Copydata__FetchBatchSizeAssignment_16");
			builder.put(grammarAccess.getCopydataAccess().getWriteBatchSizeAssignment_18(), "rule__Copydata__WriteBatchSizeAssignment_18");
			builder.put(grammarAccess.getCopydataAccess().getConditionAssignment_20(), "rule__Copydata__ConditionAssignment_20");
			builder.put(grammarAccess.getWriteCsvAccess().getNameAssignment_2(), "rule__WriteCsv__NameAssignment_2");
			builder.put(grammarAccess.getWriteCsvAccess().getSourceAssignment_4(), "rule__WriteCsv__SourceAssignment_4");
			builder.put(grammarAccess.getWriteCsvAccess().getToAssignment_6(), "rule__WriteCsv__ToAssignment_6");
			builder.put(grammarAccess.getWriteCsvAccess().getDelimAssignment_8(), "rule__WriteCsv__DelimAssignment_8");
			builder.put(grammarAccess.getWriteCsvAccess().getValueAssignment_11(), "rule__WriteCsv__ValueAssignment_11");
			builder.put(grammarAccess.getWriteCsvAccess().getConditionAssignment_14(), "rule__WriteCsv__ConditionAssignment_14");
			builder.put(grammarAccess.getLoadCsvAccess().getNameAssignment_2(), "rule__LoadCsv__NameAssignment_2");
			builder.put(grammarAccess.getLoadCsvAccess().getSourceAssignment_4(), "rule__LoadCsv__SourceAssignment_4");
			builder.put(grammarAccess.getLoadCsvAccess().getToAssignment_6(), "rule__LoadCsv__ToAssignment_6");
			builder.put(grammarAccess.getLoadCsvAccess().getDelimAssignment_8(), "rule__LoadCsv__DelimAssignment_8");
			builder.put(grammarAccess.getLoadCsvAccess().getLimitAssignment_10(), "rule__LoadCsv__LimitAssignment_10");
			builder.put(grammarAccess.getLoadCsvAccess().getDbschemaAssignment_12(), "rule__LoadCsv__DbschemaAssignment_12");
			builder.put(grammarAccess.getLoadCsvAccess().getValueAssignment_15(), "rule__LoadCsv__ValueAssignment_15");
			builder.put(grammarAccess.getLoadCsvAccess().getConditionAssignment_18(), "rule__LoadCsv__ConditionAssignment_18");
			builder.put(grammarAccess.getTransformAccess().getNameAssignment_2(), "rule__Transform__NameAssignment_2");
			builder.put(grammarAccess.getTransformAccess().getOnAssignment_4(), "rule__Transform__OnAssignment_4");
			builder.put(grammarAccess.getTransformAccess().getValueAssignment_7(), "rule__Transform__ValueAssignment_7");
			builder.put(grammarAccess.getTransformAccess().getConditionAssignment_10(), "rule__Transform__ConditionAssignment_10");
			builder.put(grammarAccess.getMongo2DbAccess().getNameAssignment_2(), "rule__Mongo2Db__NameAssignment_2");
			builder.put(grammarAccess.getMongo2DbAccess().getSourceConnStrAssignment_4(), "rule__Mongo2Db__SourceConnStrAssignment_4");
			builder.put(grammarAccess.getMongo2DbAccess().getToAssignment_6(), "rule__Mongo2Db__ToAssignment_6");
			builder.put(grammarAccess.getMongo2DbAccess().getSourceDbAssignment_8(), "rule__Mongo2Db__SourceDbAssignment_8");
			builder.put(grammarAccess.getMongo2DbAccess().getTargetDbAssignment_10(), "rule__Mongo2Db__TargetDbAssignment_10");
			builder.put(grammarAccess.getMongo2DbAccess().getTargetTableAssignment_12(), "rule__Mongo2Db__TargetTableAssignment_12");
			builder.put(grammarAccess.getMongo2DbAccess().getFilterAssignment_14(), "rule__Mongo2Db__FilterAssignment_14");
			builder.put(grammarAccess.getMongo2DbAccess().getLimitAssignment_16(), "rule__Mongo2Db__LimitAssignment_16");
			builder.put(grammarAccess.getMongo2DbAccess().getFindAttrAssignment_18(), "rule__Mongo2Db__FindAttrAssignment_18");
			builder.put(grammarAccess.getMongo2DbAccess().getApplyManipulationAssignment_20(), "rule__Mongo2Db__ApplyManipulationAssignment_20");
			builder.put(grammarAccess.getMongo2DbAccess().getOnUpdateKeyAssignment_22(), "rule__Mongo2Db__OnUpdateKeyAssignment_22");
			builder.put(grammarAccess.getMongo2DbAccess().getFetchBatchSizeAssignment_24(), "rule__Mongo2Db__FetchBatchSizeAssignment_24");
			builder.put(grammarAccess.getMongo2DbAccess().getWriteBatchSizeAssignment_26(), "rule__Mongo2Db__WriteBatchSizeAssignment_26");
			builder.put(grammarAccess.getMongo2DbAccess().getValueAssignment_29(), "rule__Mongo2Db__ValueAssignment_29");
			builder.put(grammarAccess.getMongo2DbAccess().getConditionAssignment_32(), "rule__Mongo2Db__ConditionAssignment_32");
			builder.put(grammarAccess.getFTPAccess().getNameAssignment_2(), "rule__FTP__NameAssignment_2");
			builder.put(grammarAccess.getFTPAccess().getHostAssignment_4(), "rule__FTP__HostAssignment_4");
			builder.put(grammarAccess.getFTPAccess().getPortAssignment_6(), "rule__FTP__PortAssignment_6");
			builder.put(grammarAccess.getFTPAccess().getUsernameAssignment_8(), "rule__FTP__UsernameAssignment_8");
			builder.put(grammarAccess.getFTPAccess().getPasswordAssignment_10(), "rule__FTP__PasswordAssignment_10");
			builder.put(grammarAccess.getFTPAccess().getActionAssignment_12(), "rule__FTP__ActionAssignment_12");
			builder.put(grammarAccess.getFTPAccess().getLocalDirAssignment_14(), "rule__FTP__LocalDirAssignment_14");
			builder.put(grammarAccess.getFTPAccess().getLocalFileAssignment_16(), "rule__FTP__LocalFileAssignment_16");
			builder.put(grammarAccess.getFTPAccess().getRemoteDirAssignment_18(), "rule__FTP__RemoteDirAssignment_18");
			builder.put(grammarAccess.getFTPAccess().getRemoteFileAssignment_20(), "rule__FTP__RemoteFileAssignment_20");
			builder.put(grammarAccess.getFTPAccess().getValueAssignment_23(), "rule__FTP__ValueAssignment_23");
			builder.put(grammarAccess.getFTPAccess().getConditionAssignment_26(), "rule__FTP__ConditionAssignment_26");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getNameAssignment_2(), "rule__RandForestRegressModelTraining__NameAssignment_2");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getHostAssignment_4(), "rule__RandForestRegressModelTraining__HostAssignment_4");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getPortAssignment_6(), "rule__RandForestRegressModelTraining__PortAssignment_6");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getUsernameAssignment_8(), "rule__RandForestRegressModelTraining__UsernameAssignment_8");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getPasswordAssignment_10(), "rule__RandForestRegressModelTraining__PasswordAssignment_10");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getTemplateNameAssignment_12(), "rule__RandForestRegressModelTraining__TemplateNameAssignment_12");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getProcessIdAssignment_14(), "rule__RandForestRegressModelTraining__ProcessIdAssignment_14");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getPipelineNameAssignment_16(), "rule__RandForestRegressModelTraining__PipelineNameAssignment_16");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getAlgorithmNameAssignment_18(), "rule__RandForestRegressModelTraining__AlgorithmNameAssignment_18");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getFeatureNameAssignment_20(), "rule__RandForestRegressModelTraining__FeatureNameAssignment_20");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getCallBackUrlAssignment_22(), "rule__RandForestRegressModelTraining__CallBackUrlAssignment_22");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getValueAssignment_25(), "rule__RandForestRegressModelTraining__ValueAssignment_25");
			builder.put(grammarAccess.getRandForestRegressModelTrainingAccess().getConditionAssignment_28(), "rule__RandForestRegressModelTraining__ConditionAssignment_28");
			builder.put(grammarAccess.getRandForestRegressModelTestingAccess().getNameAssignment_2(), "rule__RandForestRegressModelTesting__NameAssignment_2");
			builder.put(grammarAccess.getRandForestRegressModelTestingAccess().getHostAssignment_4(), "rule__RandForestRegressModelTesting__HostAssignment_4");
			builder.put(grammarAccess.getRandForestRegressModelTestingAccess().getPortAssignment_6(), "rule__RandForestRegressModelTesting__PortAssignment_6");
			builder.put(grammarAccess.getRandForestRegressModelTestingAccess().getUsernameAssignment_8(), "rule__RandForestRegressModelTesting__UsernameAssignment_8");
			builder.put(grammarAccess.getRandForestRegressModelTestingAccess().getPasswordAssignment_10(), "rule__RandForestRegressModelTesting__PasswordAssignment_10");
			builder.put(grammarAccess.getRandForestRegressModelTestingAccess().getValueAssignment_13(), "rule__RandForestRegressModelTesting__ValueAssignment_13");
			builder.put(grammarAccess.getRandForestRegressModelTestingAccess().getConditionAssignment_16(), "rule__RandForestRegressModelTesting__ConditionAssignment_16");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getNameAssignment_2(), "rule__RandForestRegressModelEvaluation__NameAssignment_2");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getHostAssignment_4(), "rule__RandForestRegressModelEvaluation__HostAssignment_4");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getPortAssignment_6(), "rule__RandForestRegressModelEvaluation__PortAssignment_6");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getUsernameAssignment_8(), "rule__RandForestRegressModelEvaluation__UsernameAssignment_8");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getPasswordAssignment_10(), "rule__RandForestRegressModelEvaluation__PasswordAssignment_10");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getTemplateNameAssignment_12(), "rule__RandForestRegressModelEvaluation__TemplateNameAssignment_12");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getProcessIdAssignment_14(), "rule__RandForestRegressModelEvaluation__ProcessIdAssignment_14");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getPipelineNameAssignment_16(), "rule__RandForestRegressModelEvaluation__PipelineNameAssignment_16");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getCallBackUrlAssignment_18(), "rule__RandForestRegressModelEvaluation__CallBackUrlAssignment_18");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getValueAssignment_21(), "rule__RandForestRegressModelEvaluation__ValueAssignment_21");
			builder.put(grammarAccess.getRandForestRegressModelEvaluationAccess().getConditionAssignment_24(), "rule__RandForestRegressModelEvaluation__ConditionAssignment_24");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getNameAssignment_2(), "rule__RandForestClassifyModelTraining__NameAssignment_2");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getHostAssignment_4(), "rule__RandForestClassifyModelTraining__HostAssignment_4");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getPortAssignment_6(), "rule__RandForestClassifyModelTraining__PortAssignment_6");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getUsernameAssignment_8(), "rule__RandForestClassifyModelTraining__UsernameAssignment_8");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getPasswordAssignment_10(), "rule__RandForestClassifyModelTraining__PasswordAssignment_10");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getTemplateNameAssignment_12(), "rule__RandForestClassifyModelTraining__TemplateNameAssignment_12");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getProcessIdAssignment_14(), "rule__RandForestClassifyModelTraining__ProcessIdAssignment_14");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getPipelineNameAssignment_16(), "rule__RandForestClassifyModelTraining__PipelineNameAssignment_16");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getAlgorithmNameAssignment_18(), "rule__RandForestClassifyModelTraining__AlgorithmNameAssignment_18");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getCallBackUrlAssignment_20(), "rule__RandForestClassifyModelTraining__CallBackUrlAssignment_20");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getValueAssignment_23(), "rule__RandForestClassifyModelTraining__ValueAssignment_23");
			builder.put(grammarAccess.getRandForestClassifyModelTrainingAccess().getConditionAssignment_26(), "rule__RandForestClassifyModelTraining__ConditionAssignment_26");
			builder.put(grammarAccess.getRandForestClassifyModelTestingAccess().getNameAssignment_2(), "rule__RandForestClassifyModelTesting__NameAssignment_2");
			builder.put(grammarAccess.getRandForestClassifyModelTestingAccess().getHostAssignment_4(), "rule__RandForestClassifyModelTesting__HostAssignment_4");
			builder.put(grammarAccess.getRandForestClassifyModelTestingAccess().getPortAssignment_6(), "rule__RandForestClassifyModelTesting__PortAssignment_6");
			builder.put(grammarAccess.getRandForestClassifyModelTestingAccess().getUsernameAssignment_8(), "rule__RandForestClassifyModelTesting__UsernameAssignment_8");
			builder.put(grammarAccess.getRandForestClassifyModelTestingAccess().getPasswordAssignment_10(), "rule__RandForestClassifyModelTesting__PasswordAssignment_10");
			builder.put(grammarAccess.getRandForestClassifyModelTestingAccess().getValueAssignment_13(), "rule__RandForestClassifyModelTesting__ValueAssignment_13");
			builder.put(grammarAccess.getRandForestClassifyModelTestingAccess().getConditionAssignment_16(), "rule__RandForestClassifyModelTesting__ConditionAssignment_16");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getNameAssignment_2(), "rule__RandForestClassifyModelEvaluation__NameAssignment_2");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getHostAssignment_4(), "rule__RandForestClassifyModelEvaluation__HostAssignment_4");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getPortAssignment_6(), "rule__RandForestClassifyModelEvaluation__PortAssignment_6");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getUsernameAssignment_8(), "rule__RandForestClassifyModelEvaluation__UsernameAssignment_8");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getPasswordAssignment_10(), "rule__RandForestClassifyModelEvaluation__PasswordAssignment_10");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getTemplateNameAssignment_12(), "rule__RandForestClassifyModelEvaluation__TemplateNameAssignment_12");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getProcessIdAssignment_14(), "rule__RandForestClassifyModelEvaluation__ProcessIdAssignment_14");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getPipelineNameAssignment_16(), "rule__RandForestClassifyModelEvaluation__PipelineNameAssignment_16");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getCallBackUrlAssignment_18(), "rule__RandForestClassifyModelEvaluation__CallBackUrlAssignment_18");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getValueAssignment_21(), "rule__RandForestClassifyModelEvaluation__ValueAssignment_21");
			builder.put(grammarAccess.getRandForestClassifyModelEvaluationAccess().getConditionAssignment_24(), "rule__RandForestClassifyModelEvaluation__ConditionAssignment_24");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getNameAssignment_2(), "rule__GradBoostRegressModelTraining__NameAssignment_2");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getHostAssignment_4(), "rule__GradBoostRegressModelTraining__HostAssignment_4");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getPortAssignment_6(), "rule__GradBoostRegressModelTraining__PortAssignment_6");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getUsernameAssignment_8(), "rule__GradBoostRegressModelTraining__UsernameAssignment_8");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getPasswordAssignment_10(), "rule__GradBoostRegressModelTraining__PasswordAssignment_10");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getTemplateNameAssignment_12(), "rule__GradBoostRegressModelTraining__TemplateNameAssignment_12");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getProcessIdAssignment_14(), "rule__GradBoostRegressModelTraining__ProcessIdAssignment_14");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getPipelineNameAssignment_16(), "rule__GradBoostRegressModelTraining__PipelineNameAssignment_16");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getAlgorithmNameAssignment_18(), "rule__GradBoostRegressModelTraining__AlgorithmNameAssignment_18");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getFeatureNameAssignment_20(), "rule__GradBoostRegressModelTraining__FeatureNameAssignment_20");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getCallBackUrlAssignment_22(), "rule__GradBoostRegressModelTraining__CallBackUrlAssignment_22");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getValueAssignment_25(), "rule__GradBoostRegressModelTraining__ValueAssignment_25");
			builder.put(grammarAccess.getGradBoostRegressModelTrainingAccess().getConditionAssignment_28(), "rule__GradBoostRegressModelTraining__ConditionAssignment_28");
			builder.put(grammarAccess.getGradBoostRegressModelTestingAccess().getNameAssignment_2(), "rule__GradBoostRegressModelTesting__NameAssignment_2");
			builder.put(grammarAccess.getGradBoostRegressModelTestingAccess().getHostAssignment_4(), "rule__GradBoostRegressModelTesting__HostAssignment_4");
			builder.put(grammarAccess.getGradBoostRegressModelTestingAccess().getPortAssignment_6(), "rule__GradBoostRegressModelTesting__PortAssignment_6");
			builder.put(grammarAccess.getGradBoostRegressModelTestingAccess().getUsernameAssignment_8(), "rule__GradBoostRegressModelTesting__UsernameAssignment_8");
			builder.put(grammarAccess.getGradBoostRegressModelTestingAccess().getPasswordAssignment_10(), "rule__GradBoostRegressModelTesting__PasswordAssignment_10");
			builder.put(grammarAccess.getGradBoostRegressModelTestingAccess().getValueAssignment_13(), "rule__GradBoostRegressModelTesting__ValueAssignment_13");
			builder.put(grammarAccess.getGradBoostRegressModelTestingAccess().getConditionAssignment_16(), "rule__GradBoostRegressModelTesting__ConditionAssignment_16");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getNameAssignment_2(), "rule__GradBoostRegressModelEvaluation__NameAssignment_2");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getHostAssignment_4(), "rule__GradBoostRegressModelEvaluation__HostAssignment_4");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getPortAssignment_6(), "rule__GradBoostRegressModelEvaluation__PortAssignment_6");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getUsernameAssignment_8(), "rule__GradBoostRegressModelEvaluation__UsernameAssignment_8");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getPasswordAssignment_10(), "rule__GradBoostRegressModelEvaluation__PasswordAssignment_10");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getTemplateNameAssignment_12(), "rule__GradBoostRegressModelEvaluation__TemplateNameAssignment_12");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getProcessIdAssignment_14(), "rule__GradBoostRegressModelEvaluation__ProcessIdAssignment_14");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getPipelineNameAssignment_16(), "rule__GradBoostRegressModelEvaluation__PipelineNameAssignment_16");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getCallBackUrlAssignment_18(), "rule__GradBoostRegressModelEvaluation__CallBackUrlAssignment_18");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getValueAssignment_21(), "rule__GradBoostRegressModelEvaluation__ValueAssignment_21");
			builder.put(grammarAccess.getGradBoostRegressModelEvaluationAccess().getConditionAssignment_24(), "rule__GradBoostRegressModelEvaluation__ConditionAssignment_24");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getNameAssignment_2(), "rule__GradBoostClassifyModelTraining__NameAssignment_2");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getHostAssignment_4(), "rule__GradBoostClassifyModelTraining__HostAssignment_4");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getPortAssignment_6(), "rule__GradBoostClassifyModelTraining__PortAssignment_6");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getUsernameAssignment_8(), "rule__GradBoostClassifyModelTraining__UsernameAssignment_8");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getPasswordAssignment_10(), "rule__GradBoostClassifyModelTraining__PasswordAssignment_10");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getTemplateNameAssignment_12(), "rule__GradBoostClassifyModelTraining__TemplateNameAssignment_12");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getProcessIdAssignment_14(), "rule__GradBoostClassifyModelTraining__ProcessIdAssignment_14");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getPipelineNameAssignment_16(), "rule__GradBoostClassifyModelTraining__PipelineNameAssignment_16");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getAlgorithmNameAssignment_18(), "rule__GradBoostClassifyModelTraining__AlgorithmNameAssignment_18");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getCallBackUrlAssignment_20(), "rule__GradBoostClassifyModelTraining__CallBackUrlAssignment_20");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getValueAssignment_23(), "rule__GradBoostClassifyModelTraining__ValueAssignment_23");
			builder.put(grammarAccess.getGradBoostClassifyModelTrainingAccess().getConditionAssignment_26(), "rule__GradBoostClassifyModelTraining__ConditionAssignment_26");
			builder.put(grammarAccess.getGradBoostClassifyModelTestingAccess().getNameAssignment_2(), "rule__GradBoostClassifyModelTesting__NameAssignment_2");
			builder.put(grammarAccess.getGradBoostClassifyModelTestingAccess().getHostAssignment_4(), "rule__GradBoostClassifyModelTesting__HostAssignment_4");
			builder.put(grammarAccess.getGradBoostClassifyModelTestingAccess().getPortAssignment_6(), "rule__GradBoostClassifyModelTesting__PortAssignment_6");
			builder.put(grammarAccess.getGradBoostClassifyModelTestingAccess().getUsernameAssignment_8(), "rule__GradBoostClassifyModelTesting__UsernameAssignment_8");
			builder.put(grammarAccess.getGradBoostClassifyModelTestingAccess().getPasswordAssignment_10(), "rule__GradBoostClassifyModelTesting__PasswordAssignment_10");
			builder.put(grammarAccess.getGradBoostClassifyModelTestingAccess().getValueAssignment_13(), "rule__GradBoostClassifyModelTesting__ValueAssignment_13");
			builder.put(grammarAccess.getGradBoostClassifyModelTestingAccess().getConditionAssignment_16(), "rule__GradBoostClassifyModelTesting__ConditionAssignment_16");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getNameAssignment_2(), "rule__GradBoostClassifyModelEvaluation__NameAssignment_2");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getHostAssignment_4(), "rule__GradBoostClassifyModelEvaluation__HostAssignment_4");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getPortAssignment_6(), "rule__GradBoostClassifyModelEvaluation__PortAssignment_6");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getUsernameAssignment_8(), "rule__GradBoostClassifyModelEvaluation__UsernameAssignment_8");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getPasswordAssignment_10(), "rule__GradBoostClassifyModelEvaluation__PasswordAssignment_10");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getTemplateNameAssignment_12(), "rule__GradBoostClassifyModelEvaluation__TemplateNameAssignment_12");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getProcessIdAssignment_14(), "rule__GradBoostClassifyModelEvaluation__ProcessIdAssignment_14");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getPipelineNameAssignment_16(), "rule__GradBoostClassifyModelEvaluation__PipelineNameAssignment_16");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getCallBackUrlAssignment_18(), "rule__GradBoostClassifyModelEvaluation__CallBackUrlAssignment_18");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getValueAssignment_21(), "rule__GradBoostClassifyModelEvaluation__ValueAssignment_21");
			builder.put(grammarAccess.getGradBoostClassifyModelEvaluationAccess().getConditionAssignment_24(), "rule__GradBoostClassifyModelEvaluation__ConditionAssignment_24");
			builder.put(grammarAccess.getZipAccess().getNameAssignment_2(), "rule__Zip__NameAssignment_2");
			builder.put(grammarAccess.getZipAccess().getZipFilePathAssignment_4(), "rule__Zip__ZipFilePathAssignment_4");
			builder.put(grammarAccess.getZipAccess().getZipFileNameAssignment_6(), "rule__Zip__ZipFileNameAssignment_6");
			builder.put(grammarAccess.getZipAccess().getSourceAssignment_8(), "rule__Zip__SourceAssignment_8");
			builder.put(grammarAccess.getZipAccess().getBufferSizeAssignment_10(), "rule__Zip__BufferSizeAssignment_10");
			builder.put(grammarAccess.getZipAccess().getValueAssignment_13(), "rule__Zip__ValueAssignment_13");
			builder.put(grammarAccess.getZipAccess().getConditionAssignment_16(), "rule__Zip__ConditionAssignment_16");
			builder.put(grammarAccess.getUnzipAccess().getNameAssignment_2(), "rule__Unzip__NameAssignment_2");
			builder.put(grammarAccess.getUnzipAccess().getSourceAssignment_4(), "rule__Unzip__SourceAssignment_4");
			builder.put(grammarAccess.getUnzipAccess().getDestDirAssignment_6(), "rule__Unzip__DestDirAssignment_6");
			builder.put(grammarAccess.getUnzipAccess().getBufferSizeAssignment_8(), "rule__Unzip__BufferSizeAssignment_8");
			builder.put(grammarAccess.getUnzipAccess().getValueAssignment_11(), "rule__Unzip__ValueAssignment_11");
			builder.put(grammarAccess.getUnzipAccess().getConditionAssignment_14(), "rule__Unzip__ConditionAssignment_14");
			builder.put(grammarAccess.getChecksumAccess().getNameAssignment_2(), "rule__Checksum__NameAssignment_2");
			builder.put(grammarAccess.getChecksumAccess().getHostAssignment_4(), "rule__Checksum__HostAssignment_4");
			builder.put(grammarAccess.getChecksumAccess().getPortAssignment_6(), "rule__Checksum__PortAssignment_6");
			builder.put(grammarAccess.getChecksumAccess().getUsernameAssignment_8(), "rule__Checksum__UsernameAssignment_8");
			builder.put(grammarAccess.getChecksumAccess().getPasswordAssignment_10(), "rule__Checksum__PasswordAssignment_10");
			builder.put(grammarAccess.getChecksumAccess().getLocalDirAssignment_12(), "rule__Checksum__LocalDirAssignment_12");
			builder.put(grammarAccess.getChecksumAccess().getLocalFileAssignment_14(), "rule__Checksum__LocalFileAssignment_14");
			builder.put(grammarAccess.getChecksumAccess().getRemoteDirAssignment_16(), "rule__Checksum__RemoteDirAssignment_16");
			builder.put(grammarAccess.getChecksumAccess().getRemoteFileAssignment_18(), "rule__Checksum__RemoteFileAssignment_18");
			builder.put(grammarAccess.getChecksumAccess().getValueAssignment_21(), "rule__Checksum__ValueAssignment_21");
			builder.put(grammarAccess.getChecksumAccess().getConditionAssignment_24(), "rule__Checksum__ConditionAssignment_24");
			builder.put(grammarAccess.getExpressionAccess().getLhsAssignment_1(), "rule__Expression__LhsAssignment_1");
			builder.put(grammarAccess.getExpressionAccess().getOperatorAssignment_2(), "rule__Expression__OperatorAssignment_2");
			builder.put(grammarAccess.getExpressionAccess().getRhsAssignment_3(), "rule__Expression__RhsAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
