/*
 * generated by Xtext 2.16.0
 */
package in.handyman.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import in.handyman.ide.contentassist.antlr.internal.InternalDslParser;
import in.handyman.services.DslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getOperatorAccess().getAlternatives(), "rule__Operator__Alternatives");
			builder.put(grammarAccess.getProcessAccess().getGroup(), "rule__Process__Group__0");
			builder.put(grammarAccess.getTryAccess().getGroup(), "rule__Try__Group__0");
			builder.put(grammarAccess.getFinallyAccess().getGroup(), "rule__Finally__Group__0");
			builder.put(grammarAccess.getCatchAccess().getGroup(), "rule__Catch__Group__0");
			builder.put(grammarAccess.getSendEMailAccess().getGroup(), "rule__SendEMail__Group__0");
			builder.put(grammarAccess.getDeleteFolderAccess().getGroup(), "rule__DeleteFolder__Group__0");
			builder.put(grammarAccess.getTerminalAccess().getGroup(), "rule__Terminal__Group__0");
			builder.put(grammarAccess.getExecJavaAccess().getGroup(), "rule__ExecJava__Group__0");
			builder.put(grammarAccess.getAbortAccess().getGroup(), "rule__Abort__Group__0");
			builder.put(grammarAccess.getDropfileAccess().getGroup(), "rule__Dropfile__Group__0");
			builder.put(grammarAccess.getDoozleAccess().getGroup(), "rule__Doozle__Group__0");
			builder.put(grammarAccess.getFetchAccess().getGroup(), "rule__Fetch__Group__0");
			builder.put(grammarAccess.getCallprocessAccess().getGroup(), "rule__Callprocess__Group__0");
			builder.put(grammarAccess.getForkprocessAccess().getGroup(), "rule__Forkprocess__Group__0");
			builder.put(grammarAccess.getCopydataAccess().getGroup(), "rule__Copydata__Group__0");
			builder.put(grammarAccess.getWriteCsvAccess().getGroup(), "rule__WriteCsv__Group__0");
			builder.put(grammarAccess.getLoadCsvAccess().getGroup(), "rule__LoadCsv__Group__0");
			builder.put(grammarAccess.getTransformAccess().getGroup(), "rule__Transform__Group__0");
			builder.put(grammarAccess.getDeleteSqlAccess().getGroup(), "rule__DeleteSql__Group__0");
			builder.put(grammarAccess.getUpdateSqlAccess().getGroup(), "rule__UpdateSql__Group__0");
			builder.put(grammarAccess.getInsertSqlAccess().getGroup(), "rule__InsertSql__Group__0");
			builder.put(grammarAccess.getTruncateSqlAccess().getGroup(), "rule__TruncateSql__Group__0");
			builder.put(grammarAccess.getDropSqlAccess().getGroup(), "rule__DropSql__Group__0");
			builder.put(grammarAccess.getListFilesAccess().getGroup(), "rule__ListFiles__Group__0");
			builder.put(grammarAccess.getMongo2DbAccess().getGroup(), "rule__Mongo2Db__Group__0");
			builder.put(grammarAccess.getFTPAccess().getGroup(), "rule__FTP__Group__0");
			builder.put(grammarAccess.getZipAccess().getGroup(), "rule__Zip__Group__0");
			builder.put(grammarAccess.getUnzipAccess().getGroup(), "rule__Unzip__Group__0");
			builder.put(grammarAccess.getChecksumAccess().getGroup(), "rule__Checksum__Group__0");
			builder.put(grammarAccess.getJsonTransformAccess().getGroup(), "rule__JsonTransform__Group__0");
			builder.put(grammarAccess.getJsonDeserializeAccess().getGroup(), "rule__JsonDeserialize__Group__0");
			builder.put(grammarAccess.getRestApiAccess().getGroup(), "rule__RestApi__Group__0");
			builder.put(grammarAccess.getPythonAccess().getGroup(), "rule__Python__Group__0");
			builder.put(grammarAccess.getRestAccess().getGroup(), "rule__Rest__Group__0");
			builder.put(grammarAccess.getRestPartAccess().getGroup(), "rule__RestPart__Group__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
			builder.put(grammarAccess.getProcessAccess().getNameAssignment_1(), "rule__Process__NameAssignment_1");
			builder.put(grammarAccess.getProcessAccess().getTryAssignment_3(), "rule__Process__TryAssignment_3");
			builder.put(grammarAccess.getProcessAccess().getCatchAssignment_4(), "rule__Process__CatchAssignment_4");
			builder.put(grammarAccess.getProcessAccess().getFinallyAssignment_5(), "rule__Process__FinallyAssignment_5");
			builder.put(grammarAccess.getTryAccess().getActionAssignment_2(), "rule__Try__ActionAssignment_2");
			builder.put(grammarAccess.getFinallyAccess().getActionAssignment_2(), "rule__Finally__ActionAssignment_2");
			builder.put(grammarAccess.getCatchAccess().getActionAssignment_2(), "rule__Catch__ActionAssignment_2");
			builder.put(grammarAccess.getSendEMailAccess().getNameAssignment_2(), "rule__SendEMail__NameAssignment_2");
			builder.put(grammarAccess.getSendEMailAccess().getSourceAssignment_4(), "rule__SendEMail__SourceAssignment_4");
			builder.put(grammarAccess.getSendEMailAccess().getSmtphostAssignment_6(), "rule__SendEMail__SmtphostAssignment_6");
			builder.put(grammarAccess.getSendEMailAccess().getSmtpportAssignment_8(), "rule__SendEMail__SmtpportAssignment_8");
			builder.put(grammarAccess.getSendEMailAccess().getFromAssignment_10(), "rule__SendEMail__FromAssignment_10");
			builder.put(grammarAccess.getSendEMailAccess().getPassAssignment_12(), "rule__SendEMail__PassAssignment_12");
			builder.put(grammarAccess.getSendEMailAccess().getToAssignment_14(), "rule__SendEMail__ToAssignment_14");
			builder.put(grammarAccess.getSendEMailAccess().getCcAssignment_16(), "rule__SendEMail__CcAssignment_16");
			builder.put(grammarAccess.getSendEMailAccess().getBccAssignment_18(), "rule__SendEMail__BccAssignment_18");
			builder.put(grammarAccess.getSendEMailAccess().getSubjectAssignment_20(), "rule__SendEMail__SubjectAssignment_20");
			builder.put(grammarAccess.getSendEMailAccess().getBodyAssignment_22(), "rule__SendEMail__BodyAssignment_22");
			builder.put(grammarAccess.getSendEMailAccess().getSignatureAssignment_24(), "rule__SendEMail__SignatureAssignment_24");
			builder.put(grammarAccess.getSendEMailAccess().getValueAssignment_27(), "rule__SendEMail__ValueAssignment_27");
			builder.put(grammarAccess.getSendEMailAccess().getConditionAssignment_30(), "rule__SendEMail__ConditionAssignment_30");
			builder.put(grammarAccess.getDeleteFolderAccess().getNameAssignment_2(), "rule__DeleteFolder__NameAssignment_2");
			builder.put(grammarAccess.getDeleteFolderAccess().getFoldersourceAssignment_4(), "rule__DeleteFolder__FoldersourceAssignment_4");
			builder.put(grammarAccess.getDeleteFolderAccess().getZipsourceAssignment_6(), "rule__DeleteFolder__ZipsourceAssignment_6");
			builder.put(grammarAccess.getDeleteFolderAccess().getValueAssignment_8(), "rule__DeleteFolder__ValueAssignment_8");
			builder.put(grammarAccess.getDeleteFolderAccess().getConditionAssignment_11(), "rule__DeleteFolder__ConditionAssignment_11");
			builder.put(grammarAccess.getTerminalAccess().getNameAssignment_2(), "rule__Terminal__NameAssignment_2");
			builder.put(grammarAccess.getTerminalAccess().getIdAssignment_4(), "rule__Terminal__IdAssignment_4");
			builder.put(grammarAccess.getTerminalAccess().getValueAssignment_7(), "rule__Terminal__ValueAssignment_7");
			builder.put(grammarAccess.getTerminalAccess().getConditionAssignment_10(), "rule__Terminal__ConditionAssignment_10");
			builder.put(grammarAccess.getExecJavaAccess().getNameAssignment_2(), "rule__ExecJava__NameAssignment_2");
			builder.put(grammarAccess.getExecJavaAccess().getClassFqnAssignment_4(), "rule__ExecJava__ClassFqnAssignment_4");
			builder.put(grammarAccess.getExecJavaAccess().getDbSrcAssignment_6(), "rule__ExecJava__DbSrcAssignment_6");
			builder.put(grammarAccess.getExecJavaAccess().getValueAssignment_8(), "rule__ExecJava__ValueAssignment_8");
			builder.put(grammarAccess.getExecJavaAccess().getConditionAssignment_11(), "rule__ExecJava__ConditionAssignment_11");
			builder.put(grammarAccess.getAbortAccess().getNameAssignment_2(), "rule__Abort__NameAssignment_2");
			builder.put(grammarAccess.getAbortAccess().getValueAssignment_4(), "rule__Abort__ValueAssignment_4");
			builder.put(grammarAccess.getAbortAccess().getConditionAssignment_7(), "rule__Abort__ConditionAssignment_7");
			builder.put(grammarAccess.getDropfileAccess().getNameAssignment_2(), "rule__Dropfile__NameAssignment_2");
			builder.put(grammarAccess.getDropfileAccess().getTargetAssignment_4(), "rule__Dropfile__TargetAssignment_4");
			builder.put(grammarAccess.getDropfileAccess().getConditionAssignment_6(), "rule__Dropfile__ConditionAssignment_6");
			builder.put(grammarAccess.getDoozleAccess().getNameAssignment_2(), "rule__Doozle__NameAssignment_2");
			builder.put(grammarAccess.getDoozleAccess().getTargetAssignment_4(), "rule__Doozle__TargetAssignment_4");
			builder.put(grammarAccess.getDoozleAccess().getOnAssignment_6(), "rule__Doozle__OnAssignment_6");
			builder.put(grammarAccess.getDoozleAccess().getValueAssignment_9(), "rule__Doozle__ValueAssignment_9");
			builder.put(grammarAccess.getDoozleAccess().getConditionAssignment_12(), "rule__Doozle__ConditionAssignment_12");
			builder.put(grammarAccess.getFetchAccess().getNameAssignment_2(), "rule__Fetch__NameAssignment_2");
			builder.put(grammarAccess.getFetchAccess().getSourceAssignment_4(), "rule__Fetch__SourceAssignment_4");
			builder.put(grammarAccess.getFetchAccess().getValueAssignment_7(), "rule__Fetch__ValueAssignment_7");
			builder.put(grammarAccess.getFetchAccess().getConditionAssignment_10(), "rule__Fetch__ConditionAssignment_10");
			builder.put(grammarAccess.getCallprocessAccess().getNameAssignment_2(), "rule__Callprocess__NameAssignment_2");
			builder.put(grammarAccess.getCallprocessAccess().getTargetAssignment_4(), "rule__Callprocess__TargetAssignment_4");
			builder.put(grammarAccess.getCallprocessAccess().getSourceAssignment_6(), "rule__Callprocess__SourceAssignment_6");
			builder.put(grammarAccess.getCallprocessAccess().getDatasourceAssignment_8(), "rule__Callprocess__DatasourceAssignment_8");
			builder.put(grammarAccess.getCallprocessAccess().getValueAssignment_11(), "rule__Callprocess__ValueAssignment_11");
			builder.put(grammarAccess.getCallprocessAccess().getConditionAssignment_14(), "rule__Callprocess__ConditionAssignment_14");
			builder.put(grammarAccess.getForkprocessAccess().getNameAssignment_2(), "rule__Forkprocess__NameAssignment_2");
			builder.put(grammarAccess.getForkprocessAccess().getTargetAssignment_4(), "rule__Forkprocess__TargetAssignment_4");
			builder.put(grammarAccess.getForkprocessAccess().getSourceAssignment_6(), "rule__Forkprocess__SourceAssignment_6");
			builder.put(grammarAccess.getForkprocessAccess().getDatasourceAssignment_8(), "rule__Forkprocess__DatasourceAssignment_8");
			builder.put(grammarAccess.getForkprocessAccess().getValueAssignment_11(), "rule__Forkprocess__ValueAssignment_11");
			builder.put(grammarAccess.getForkprocessAccess().getForkBatchSizeAssignment_14(), "rule__Forkprocess__ForkBatchSizeAssignment_14");
			builder.put(grammarAccess.getForkprocessAccess().getConditionAssignment_16(), "rule__Forkprocess__ConditionAssignment_16");
			builder.put(grammarAccess.getCopydataAccess().getNameAssignment_2(), "rule__Copydata__NameAssignment_2");
			builder.put(grammarAccess.getCopydataAccess().getSourceAssignment_4(), "rule__Copydata__SourceAssignment_4");
			builder.put(grammarAccess.getCopydataAccess().getToAssignment_6(), "rule__Copydata__ToAssignment_6");
			builder.put(grammarAccess.getCopydataAccess().getTargetAssignment_8(), "rule__Copydata__TargetAssignment_8");
			builder.put(grammarAccess.getCopydataAccess().getLimitAssignment_10(), "rule__Copydata__LimitAssignment_10");
			builder.put(grammarAccess.getCopydataAccess().getValueAssignment_13(), "rule__Copydata__ValueAssignment_13");
			builder.put(grammarAccess.getCopydataAccess().getConditionAssignment_16(), "rule__Copydata__ConditionAssignment_16");
			builder.put(grammarAccess.getWriteCsvAccess().getNameAssignment_2(), "rule__WriteCsv__NameAssignment_2");
			builder.put(grammarAccess.getWriteCsvAccess().getSourceAssignment_4(), "rule__WriteCsv__SourceAssignment_4");
			builder.put(grammarAccess.getWriteCsvAccess().getToAssignment_6(), "rule__WriteCsv__ToAssignment_6");
			builder.put(grammarAccess.getWriteCsvAccess().getDelimAssignment_8(), "rule__WriteCsv__DelimAssignment_8");
			builder.put(grammarAccess.getWriteCsvAccess().getValueAssignment_11(), "rule__WriteCsv__ValueAssignment_11");
			builder.put(grammarAccess.getWriteCsvAccess().getConditionAssignment_14(), "rule__WriteCsv__ConditionAssignment_14");
			builder.put(grammarAccess.getLoadCsvAccess().getNameAssignment_2(), "rule__LoadCsv__NameAssignment_2");
			builder.put(grammarAccess.getLoadCsvAccess().getPidAssignment_4(), "rule__LoadCsv__PidAssignment_4");
			builder.put(grammarAccess.getLoadCsvAccess().getSourceAssignment_6(), "rule__LoadCsv__SourceAssignment_6");
			builder.put(grammarAccess.getLoadCsvAccess().getToAssignment_8(), "rule__LoadCsv__ToAssignment_8");
			builder.put(grammarAccess.getLoadCsvAccess().getDelimAssignment_10(), "rule__LoadCsv__DelimAssignment_10");
			builder.put(grammarAccess.getLoadCsvAccess().getLimitAssignment_12(), "rule__LoadCsv__LimitAssignment_12");
			builder.put(grammarAccess.getLoadCsvAccess().getValueAssignment_15(), "rule__LoadCsv__ValueAssignment_15");
			builder.put(grammarAccess.getLoadCsvAccess().getConditionAssignment_18(), "rule__LoadCsv__ConditionAssignment_18");
			builder.put(grammarAccess.getTransformAccess().getNameAssignment_2(), "rule__Transform__NameAssignment_2");
			builder.put(grammarAccess.getTransformAccess().getOnAssignment_4(), "rule__Transform__OnAssignment_4");
			builder.put(grammarAccess.getTransformAccess().getValueAssignment_7(), "rule__Transform__ValueAssignment_7");
			builder.put(grammarAccess.getTransformAccess().getConditionAssignment_10(), "rule__Transform__ConditionAssignment_10");
			builder.put(grammarAccess.getDeleteSqlAccess().getNameAssignment_2(), "rule__DeleteSql__NameAssignment_2");
			builder.put(grammarAccess.getDeleteSqlAccess().getOnAssignment_4(), "rule__DeleteSql__OnAssignment_4");
			builder.put(grammarAccess.getDeleteSqlAccess().getValueAssignment_7(), "rule__DeleteSql__ValueAssignment_7");
			builder.put(grammarAccess.getDeleteSqlAccess().getConditionAssignment_10(), "rule__DeleteSql__ConditionAssignment_10");
			builder.put(grammarAccess.getUpdateSqlAccess().getNameAssignment_2(), "rule__UpdateSql__NameAssignment_2");
			builder.put(grammarAccess.getUpdateSqlAccess().getOnAssignment_4(), "rule__UpdateSql__OnAssignment_4");
			builder.put(grammarAccess.getUpdateSqlAccess().getValueAssignment_7(), "rule__UpdateSql__ValueAssignment_7");
			builder.put(grammarAccess.getUpdateSqlAccess().getConditionAssignment_10(), "rule__UpdateSql__ConditionAssignment_10");
			builder.put(grammarAccess.getInsertSqlAccess().getNameAssignment_2(), "rule__InsertSql__NameAssignment_2");
			builder.put(grammarAccess.getInsertSqlAccess().getOnAssignment_4(), "rule__InsertSql__OnAssignment_4");
			builder.put(grammarAccess.getInsertSqlAccess().getValueAssignment_7(), "rule__InsertSql__ValueAssignment_7");
			builder.put(grammarAccess.getInsertSqlAccess().getConditionAssignment_10(), "rule__InsertSql__ConditionAssignment_10");
			builder.put(grammarAccess.getTruncateSqlAccess().getNameAssignment_2(), "rule__TruncateSql__NameAssignment_2");
			builder.put(grammarAccess.getTruncateSqlAccess().getOnAssignment_4(), "rule__TruncateSql__OnAssignment_4");
			builder.put(grammarAccess.getTruncateSqlAccess().getValueAssignment_7(), "rule__TruncateSql__ValueAssignment_7");
			builder.put(grammarAccess.getTruncateSqlAccess().getConditionAssignment_10(), "rule__TruncateSql__ConditionAssignment_10");
			builder.put(grammarAccess.getDropSqlAccess().getNameAssignment_2(), "rule__DropSql__NameAssignment_2");
			builder.put(grammarAccess.getDropSqlAccess().getOnAssignment_4(), "rule__DropSql__OnAssignment_4");
			builder.put(grammarAccess.getDropSqlAccess().getValueAssignment_7(), "rule__DropSql__ValueAssignment_7");
			builder.put(grammarAccess.getDropSqlAccess().getConditionAssignment_10(), "rule__DropSql__ConditionAssignment_10");
			builder.put(grammarAccess.getListFilesAccess().getNameAssignment_2(), "rule__ListFiles__NameAssignment_2");
			builder.put(grammarAccess.getListFilesAccess().getSourceAssignment_4(), "rule__ListFiles__SourceAssignment_4");
			builder.put(grammarAccess.getListFilesAccess().getToAssignment_6(), "rule__ListFiles__ToAssignment_6");
			builder.put(grammarAccess.getListFilesAccess().getTargetTableAssignment_8(), "rule__ListFiles__TargetTableAssignment_8");
			builder.put(grammarAccess.getListFilesAccess().getValueAssignment_11(), "rule__ListFiles__ValueAssignment_11");
			builder.put(grammarAccess.getListFilesAccess().getConditionAssignment_14(), "rule__ListFiles__ConditionAssignment_14");
			builder.put(grammarAccess.getMongo2DbAccess().getNameAssignment_2(), "rule__Mongo2Db__NameAssignment_2");
			builder.put(grammarAccess.getMongo2DbAccess().getSourceConnStrAssignment_4(), "rule__Mongo2Db__SourceConnStrAssignment_4");
			builder.put(grammarAccess.getMongo2DbAccess().getToAssignment_6(), "rule__Mongo2Db__ToAssignment_6");
			builder.put(grammarAccess.getMongo2DbAccess().getSourceDbAssignment_8(), "rule__Mongo2Db__SourceDbAssignment_8");
			builder.put(grammarAccess.getMongo2DbAccess().getTargetDbAssignment_10(), "rule__Mongo2Db__TargetDbAssignment_10");
			builder.put(grammarAccess.getMongo2DbAccess().getTargetTableAssignment_12(), "rule__Mongo2Db__TargetTableAssignment_12");
			builder.put(grammarAccess.getMongo2DbAccess().getFilterAssignment_14(), "rule__Mongo2Db__FilterAssignment_14");
			builder.put(grammarAccess.getMongo2DbAccess().getLimitAssignment_16(), "rule__Mongo2Db__LimitAssignment_16");
			builder.put(grammarAccess.getMongo2DbAccess().getFindAttrAssignment_18(), "rule__Mongo2Db__FindAttrAssignment_18");
			builder.put(grammarAccess.getMongo2DbAccess().getApplyManipulationAssignment_20(), "rule__Mongo2Db__ApplyManipulationAssignment_20");
			builder.put(grammarAccess.getMongo2DbAccess().getOnUpdateKeyAssignment_22(), "rule__Mongo2Db__OnUpdateKeyAssignment_22");
			builder.put(grammarAccess.getMongo2DbAccess().getFetchBatchSizeAssignment_24(), "rule__Mongo2Db__FetchBatchSizeAssignment_24");
			builder.put(grammarAccess.getMongo2DbAccess().getWriteBatchSizeAssignment_26(), "rule__Mongo2Db__WriteBatchSizeAssignment_26");
			builder.put(grammarAccess.getMongo2DbAccess().getValueAssignment_29(), "rule__Mongo2Db__ValueAssignment_29");
			builder.put(grammarAccess.getMongo2DbAccess().getConditionAssignment_32(), "rule__Mongo2Db__ConditionAssignment_32");
			builder.put(grammarAccess.getFTPAccess().getNameAssignment_2(), "rule__FTP__NameAssignment_2");
			builder.put(grammarAccess.getFTPAccess().getHostAssignment_4(), "rule__FTP__HostAssignment_4");
			builder.put(grammarAccess.getFTPAccess().getPortAssignment_6(), "rule__FTP__PortAssignment_6");
			builder.put(grammarAccess.getFTPAccess().getUsernameAssignment_8(), "rule__FTP__UsernameAssignment_8");
			builder.put(grammarAccess.getFTPAccess().getPasswordAssignment_10(), "rule__FTP__PasswordAssignment_10");
			builder.put(grammarAccess.getFTPAccess().getActionAssignment_12(), "rule__FTP__ActionAssignment_12");
			builder.put(grammarAccess.getFTPAccess().getLocalDirAssignment_14(), "rule__FTP__LocalDirAssignment_14");
			builder.put(grammarAccess.getFTPAccess().getLocalFileAssignment_16(), "rule__FTP__LocalFileAssignment_16");
			builder.put(grammarAccess.getFTPAccess().getRemoteDirAssignment_18(), "rule__FTP__RemoteDirAssignment_18");
			builder.put(grammarAccess.getFTPAccess().getRemoteFileAssignment_20(), "rule__FTP__RemoteFileAssignment_20");
			builder.put(grammarAccess.getFTPAccess().getSourceAssignment_22(), "rule__FTP__SourceAssignment_22");
			builder.put(grammarAccess.getFTPAccess().getTargetTableAssignment_24(), "rule__FTP__TargetTableAssignment_24");
			builder.put(grammarAccess.getFTPAccess().getValueAssignment_27(), "rule__FTP__ValueAssignment_27");
			builder.put(grammarAccess.getFTPAccess().getConditionAssignment_30(), "rule__FTP__ConditionAssignment_30");
			builder.put(grammarAccess.getZipAccess().getNameAssignment_2(), "rule__Zip__NameAssignment_2");
			builder.put(grammarAccess.getZipAccess().getZipFilePathAssignment_4(), "rule__Zip__ZipFilePathAssignment_4");
			builder.put(grammarAccess.getZipAccess().getZipFileNameAssignment_6(), "rule__Zip__ZipFileNameAssignment_6");
			builder.put(grammarAccess.getZipAccess().getSourceAssignment_8(), "rule__Zip__SourceAssignment_8");
			builder.put(grammarAccess.getZipAccess().getBufferSizeAssignment_10(), "rule__Zip__BufferSizeAssignment_10");
			builder.put(grammarAccess.getZipAccess().getValueAssignment_13(), "rule__Zip__ValueAssignment_13");
			builder.put(grammarAccess.getZipAccess().getConditionAssignment_16(), "rule__Zip__ConditionAssignment_16");
			builder.put(grammarAccess.getUnzipAccess().getNameAssignment_2(), "rule__Unzip__NameAssignment_2");
			builder.put(grammarAccess.getUnzipAccess().getSourceAssignment_4(), "rule__Unzip__SourceAssignment_4");
			builder.put(grammarAccess.getUnzipAccess().getDestDirAssignment_6(), "rule__Unzip__DestDirAssignment_6");
			builder.put(grammarAccess.getUnzipAccess().getBufferSizeAssignment_8(), "rule__Unzip__BufferSizeAssignment_8");
			builder.put(grammarAccess.getUnzipAccess().getValueAssignment_11(), "rule__Unzip__ValueAssignment_11");
			builder.put(grammarAccess.getUnzipAccess().getConditionAssignment_14(), "rule__Unzip__ConditionAssignment_14");
			builder.put(grammarAccess.getChecksumAccess().getNameAssignment_2(), "rule__Checksum__NameAssignment_2");
			builder.put(grammarAccess.getChecksumAccess().getHostAssignment_4(), "rule__Checksum__HostAssignment_4");
			builder.put(grammarAccess.getChecksumAccess().getPortAssignment_6(), "rule__Checksum__PortAssignment_6");
			builder.put(grammarAccess.getChecksumAccess().getUsernameAssignment_8(), "rule__Checksum__UsernameAssignment_8");
			builder.put(grammarAccess.getChecksumAccess().getPasswordAssignment_10(), "rule__Checksum__PasswordAssignment_10");
			builder.put(grammarAccess.getChecksumAccess().getLocalDirAssignment_12(), "rule__Checksum__LocalDirAssignment_12");
			builder.put(grammarAccess.getChecksumAccess().getLocalFileAssignment_14(), "rule__Checksum__LocalFileAssignment_14");
			builder.put(grammarAccess.getChecksumAccess().getRemoteDirAssignment_16(), "rule__Checksum__RemoteDirAssignment_16");
			builder.put(grammarAccess.getChecksumAccess().getRemoteFileAssignment_18(), "rule__Checksum__RemoteFileAssignment_18");
			builder.put(grammarAccess.getChecksumAccess().getValueAssignment_21(), "rule__Checksum__ValueAssignment_21");
			builder.put(grammarAccess.getChecksumAccess().getConditionAssignment_24(), "rule__Checksum__ConditionAssignment_24");
			builder.put(grammarAccess.getJsonTransformAccess().getNameAssignment_2(), "rule__JsonTransform__NameAssignment_2");
			builder.put(grammarAccess.getJsonTransformAccess().getSourceAssignment_4(), "rule__JsonTransform__SourceAssignment_4");
			builder.put(grammarAccess.getJsonTransformAccess().getTargetTableAssignment_6(), "rule__JsonTransform__TargetTableAssignment_6");
			builder.put(grammarAccess.getJsonTransformAccess().getValueAssignment_9(), "rule__JsonTransform__ValueAssignment_9");
			builder.put(grammarAccess.getJsonTransformAccess().getConditionAssignment_12(), "rule__JsonTransform__ConditionAssignment_12");
			builder.put(grammarAccess.getJsonDeserializeAccess().getNameAssignment_2(), "rule__JsonDeserialize__NameAssignment_2");
			builder.put(grammarAccess.getJsonDeserializeAccess().getSourceAssignment_4(), "rule__JsonDeserialize__SourceAssignment_4");
			builder.put(grammarAccess.getJsonDeserializeAccess().getTargetTableAssignment_6(), "rule__JsonDeserialize__TargetTableAssignment_6");
			builder.put(grammarAccess.getJsonDeserializeAccess().getInputAssignment_8(), "rule__JsonDeserialize__InputAssignment_8");
			builder.put(grammarAccess.getJsonDeserializeAccess().getValueAssignment_11(), "rule__JsonDeserialize__ValueAssignment_11");
			builder.put(grammarAccess.getJsonDeserializeAccess().getConditionAssignment_14(), "rule__JsonDeserialize__ConditionAssignment_14");
			builder.put(grammarAccess.getRestApiAccess().getNameAssignment_2(), "rule__RestApi__NameAssignment_2");
			builder.put(grammarAccess.getRestApiAccess().getUrlAssignment_4(), "rule__RestApi__UrlAssignment_4");
			builder.put(grammarAccess.getRestApiAccess().getMethodAssignment_6(), "rule__RestApi__MethodAssignment_6");
			builder.put(grammarAccess.getRestApiAccess().getPropertyAssignment_8(), "rule__RestApi__PropertyAssignment_8");
			builder.put(grammarAccess.getRestApiAccess().getPayloadAssignment_10(), "rule__RestApi__PayloadAssignment_10");
			builder.put(grammarAccess.getRestApiAccess().getSourceAssignment_12(), "rule__RestApi__SourceAssignment_12");
			builder.put(grammarAccess.getRestApiAccess().getTargetTableAssignment_14(), "rule__RestApi__TargetTableAssignment_14");
			builder.put(grammarAccess.getRestApiAccess().getValueAssignment_17(), "rule__RestApi__ValueAssignment_17");
			builder.put(grammarAccess.getRestApiAccess().getConditionAssignment_20(), "rule__RestApi__ConditionAssignment_20");
			builder.put(grammarAccess.getPythonAccess().getNameAssignment_2(), "rule__Python__NameAssignment_2");
			builder.put(grammarAccess.getPythonAccess().getSourceAssignment_4(), "rule__Python__SourceAssignment_4");
			builder.put(grammarAccess.getPythonAccess().getTargetAssignment_6(), "rule__Python__TargetAssignment_6");
			builder.put(grammarAccess.getPythonAccess().getValueAssignment_9(), "rule__Python__ValueAssignment_9");
			builder.put(grammarAccess.getPythonAccess().getConditionAssignment_12(), "rule__Python__ConditionAssignment_12");
			builder.put(grammarAccess.getRestAccess().getNameAssignment_2(), "rule__Rest__NameAssignment_2");
			builder.put(grammarAccess.getRestAccess().getAuthtokenAssignment_4(), "rule__Rest__AuthtokenAssignment_4");
			builder.put(grammarAccess.getRestAccess().getUrlAssignment_6(), "rule__Rest__UrlAssignment_6");
			builder.put(grammarAccess.getRestAccess().getMethodAssignment_8(), "rule__Rest__MethodAssignment_8");
			builder.put(grammarAccess.getRestAccess().getResourcedatafromAssignment_11(), "rule__Rest__ResourcedatafromAssignment_11");
			builder.put(grammarAccess.getRestAccess().getUrldataAssignment_14(), "rule__Rest__UrldataAssignment_14");
			builder.put(grammarAccess.getRestAccess().getHeaderdatafromAssignment_17(), "rule__Rest__HeaderdatafromAssignment_17");
			builder.put(grammarAccess.getRestAccess().getHeaderdataAssignment_20(), "rule__Rest__HeaderdataAssignment_20");
			builder.put(grammarAccess.getRestAccess().getPostdatafromAssignment_23(), "rule__Rest__PostdatafromAssignment_23");
			builder.put(grammarAccess.getRestAccess().getParentNameAssignment_28(), "rule__Rest__ParentNameAssignment_28");
			builder.put(grammarAccess.getRestAccess().getParentdataAssignment_29(), "rule__Rest__ParentdataAssignment_29");
			builder.put(grammarAccess.getRestAccess().getPartsAssignment_30(), "rule__Rest__PartsAssignment_30");
			builder.put(grammarAccess.getRestAccess().getAckdatatoAssignment_33(), "rule__Rest__AckdatatoAssignment_33");
			builder.put(grammarAccess.getRestAccess().getAckdataAssignment_36(), "rule__Rest__AckdataAssignment_36");
			builder.put(grammarAccess.getRestAccess().getConditionAssignment_40(), "rule__Rest__ConditionAssignment_40");
			builder.put(grammarAccess.getRestPartAccess().getPartNameAssignment_2(), "rule__RestPart__PartNameAssignment_2");
			builder.put(grammarAccess.getRestPartAccess().getPartDataAssignment_4(), "rule__RestPart__PartDataAssignment_4");
			builder.put(grammarAccess.getExpressionAccess().getLhsAssignment_1(), "rule__Expression__LhsAssignment_1");
			builder.put(grammarAccess.getExpressionAccess().getOperatorAssignment_2(), "rule__Expression__OperatorAssignment_2");
			builder.put(grammarAccess.getExpressionAccess().getRhsAssignment_3(), "rule__Expression__RhsAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
