/**
 * generated by Xtext 2.16.0
 */
package in.handyman.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Checksum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.Checksum#getHost <em>Host</em>}</li>
 *   <li>{@link in.handyman.dsl.Checksum#getPort <em>Port</em>}</li>
 *   <li>{@link in.handyman.dsl.Checksum#getUsername <em>Username</em>}</li>
 *   <li>{@link in.handyman.dsl.Checksum#getPassword <em>Password</em>}</li>
 *   <li>{@link in.handyman.dsl.Checksum#getLocalDir <em>Local Dir</em>}</li>
 *   <li>{@link in.handyman.dsl.Checksum#getLocalFile <em>Local File</em>}</li>
 *   <li>{@link in.handyman.dsl.Checksum#getRemoteDir <em>Remote Dir</em>}</li>
 *   <li>{@link in.handyman.dsl.Checksum#getRemoteFile <em>Remote File</em>}</li>
 *   <li>{@link in.handyman.dsl.Checksum#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see in.handyman.dsl.DslPackage#getChecksum()
 * @model
 * @generated
 */
public interface Checksum extends Action
{
  /**
   * Returns the value of the '<em><b>Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Host</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Host</em>' attribute.
   * @see #setHost(String)
   * @see in.handyman.dsl.DslPackage#getChecksum_Host()
   * @model
   * @generated
   */
  String getHost();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Checksum#getHost <em>Host</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Host</em>' attribute.
   * @see #getHost()
   * @generated
   */
  void setHost(String value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(String)
   * @see in.handyman.dsl.DslPackage#getChecksum_Port()
   * @model
   * @generated
   */
  String getPort();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Checksum#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(String value);

  /**
   * Returns the value of the '<em><b>Username</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Username</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Username</em>' attribute.
   * @see #setUsername(String)
   * @see in.handyman.dsl.DslPackage#getChecksum_Username()
   * @model
   * @generated
   */
  String getUsername();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Checksum#getUsername <em>Username</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Username</em>' attribute.
   * @see #getUsername()
   * @generated
   */
  void setUsername(String value);

  /**
   * Returns the value of the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Password</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Password</em>' attribute.
   * @see #setPassword(String)
   * @see in.handyman.dsl.DslPackage#getChecksum_Password()
   * @model
   * @generated
   */
  String getPassword();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Checksum#getPassword <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Password</em>' attribute.
   * @see #getPassword()
   * @generated
   */
  void setPassword(String value);

  /**
   * Returns the value of the '<em><b>Local Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Local Dir</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local Dir</em>' attribute.
   * @see #setLocalDir(String)
   * @see in.handyman.dsl.DslPackage#getChecksum_LocalDir()
   * @model
   * @generated
   */
  String getLocalDir();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Checksum#getLocalDir <em>Local Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Local Dir</em>' attribute.
   * @see #getLocalDir()
   * @generated
   */
  void setLocalDir(String value);

  /**
   * Returns the value of the '<em><b>Local File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Local File</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local File</em>' attribute.
   * @see #setLocalFile(String)
   * @see in.handyman.dsl.DslPackage#getChecksum_LocalFile()
   * @model
   * @generated
   */
  String getLocalFile();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Checksum#getLocalFile <em>Local File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Local File</em>' attribute.
   * @see #getLocalFile()
   * @generated
   */
  void setLocalFile(String value);

  /**
   * Returns the value of the '<em><b>Remote Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Remote Dir</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Remote Dir</em>' attribute.
   * @see #setRemoteDir(String)
   * @see in.handyman.dsl.DslPackage#getChecksum_RemoteDir()
   * @model
   * @generated
   */
  String getRemoteDir();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Checksum#getRemoteDir <em>Remote Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Remote Dir</em>' attribute.
   * @see #getRemoteDir()
   * @generated
   */
  void setRemoteDir(String value);

  /**
   * Returns the value of the '<em><b>Remote File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Remote File</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Remote File</em>' attribute.
   * @see #setRemoteFile(String)
   * @see in.handyman.dsl.DslPackage#getChecksum_RemoteFile()
   * @model
   * @generated
   */
  String getRemoteFile();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Checksum#getRemoteFile <em>Remote File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Remote File</em>' attribute.
   * @see #getRemoteFile()
   * @generated
   */
  void setRemoteFile(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see in.handyman.dsl.DslPackage#getChecksum_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Checksum#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Checksum
