/**
 * generated by Xtext 2.16.0
 */
package in.handyman.dsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see in.handyman.dsl.DslPackage
 * @generated
 */
public interface DslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslFactory eINSTANCE = in.handyman.dsl.impl.DslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Process</em>'.
   * @generated
   */
  Process createProcess();

  /**
   * Returns a new object of class '<em>Try</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Try</em>'.
   * @generated
   */
  Try createTry();

  /**
   * Returns a new object of class '<em>Finally</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Finally</em>'.
   * @generated
   */
  Finally createFinally();

  /**
   * Returns a new object of class '<em>Catch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Catch</em>'.
   * @generated
   */
  Catch createCatch();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Send EMail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Send EMail</em>'.
   * @generated
   */
  SendEMail createSendEMail();

  /**
   * Returns a new object of class '<em>Delete Folder</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Folder</em>'.
   * @generated
   */
  DeleteFolder createDeleteFolder();

  /**
   * Returns a new object of class '<em>Terminal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminal</em>'.
   * @generated
   */
  Terminal createTerminal();

  /**
   * Returns a new object of class '<em>Exec Java</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exec Java</em>'.
   * @generated
   */
  ExecJava createExecJava();

  /**
   * Returns a new object of class '<em>Abort</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abort</em>'.
   * @generated
   */
  Abort createAbort();

  /**
   * Returns a new object of class '<em>Dropfile</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dropfile</em>'.
   * @generated
   */
  Dropfile createDropfile();

  /**
   * Returns a new object of class '<em>Doozle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Doozle</em>'.
   * @generated
   */
  Doozle createDoozle();

  /**
   * Returns a new object of class '<em>Fetch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fetch</em>'.
   * @generated
   */
  Fetch createFetch();

  /**
   * Returns a new object of class '<em>Callprocess</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Callprocess</em>'.
   * @generated
   */
  Callprocess createCallprocess();

  /**
   * Returns a new object of class '<em>Forkprocess</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Forkprocess</em>'.
   * @generated
   */
  Forkprocess createForkprocess();

  /**
   * Returns a new object of class '<em>Copydata</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Copydata</em>'.
   * @generated
   */
  Copydata createCopydata();

  /**
   * Returns a new object of class '<em>Write Csv</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Write Csv</em>'.
   * @generated
   */
  WriteCsv createWriteCsv();

  /**
   * Returns a new object of class '<em>Load Csv</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Load Csv</em>'.
   * @generated
   */
  LoadCsv createLoadCsv();

  /**
   * Returns a new object of class '<em>Transform</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transform</em>'.
   * @generated
   */
  Transform createTransform();

  /**
   * Returns a new object of class '<em>Delete Sql</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Sql</em>'.
   * @generated
   */
  DeleteSql createDeleteSql();

  /**
   * Returns a new object of class '<em>Update Sql</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Update Sql</em>'.
   * @generated
   */
  UpdateSql createUpdateSql();

  /**
   * Returns a new object of class '<em>Insert Sql</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insert Sql</em>'.
   * @generated
   */
  InsertSql createInsertSql();

  /**
   * Returns a new object of class '<em>Truncate Sql</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Truncate Sql</em>'.
   * @generated
   */
  TruncateSql createTruncateSql();

  /**
   * Returns a new object of class '<em>Drop Sql</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Drop Sql</em>'.
   * @generated
   */
  DropSql createDropSql();

  /**
   * Returns a new object of class '<em>List Files</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Files</em>'.
   * @generated
   */
  ListFiles createListFiles();

  /**
   * Returns a new object of class '<em>Mongo2 Db</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mongo2 Db</em>'.
   * @generated
   */
  Mongo2Db createMongo2Db();

  /**
   * Returns a new object of class '<em>FTP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FTP</em>'.
   * @generated
   */
  FTP createFTP();

  /**
   * Returns a new object of class '<em>Zip</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Zip</em>'.
   * @generated
   */
  Zip createZip();

  /**
   * Returns a new object of class '<em>Unzip</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unzip</em>'.
   * @generated
   */
  Unzip createUnzip();

  /**
   * Returns a new object of class '<em>Checksum</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Checksum</em>'.
   * @generated
   */
  Checksum createChecksum();

  /**
   * Returns a new object of class '<em>Json Transform</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Transform</em>'.
   * @generated
   */
  JsonTransform createJsonTransform();

  /**
   * Returns a new object of class '<em>Json Deserialize</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Json Deserialize</em>'.
   * @generated
   */
  JsonDeserialize createJsonDeserialize();

  /**
   * Returns a new object of class '<em>Rest Api</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rest Api</em>'.
   * @generated
   */
  RestApi createRestApi();

  /**
   * Returns a new object of class '<em>Python</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Python</em>'.
   * @generated
   */
  Python createPython();

  /**
   * Returns a new object of class '<em>Rest</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rest</em>'.
   * @generated
   */
  Rest createRest();

  /**
   * Returns a new object of class '<em>Rest Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rest Part</em>'.
   * @generated
   */
  RestPart createRestPart();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DslPackage getDslPackage();

} //DslFactory
