/**
 * generated by Xtext 2.16.0
 */
package in.handyman.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mongo2 Db</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getSourceConnStr <em>Source Conn Str</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getTo <em>To</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getSourceDb <em>Source Db</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getTargetDb <em>Target Db</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getTargetTable <em>Target Table</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getFilter <em>Filter</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getLimit <em>Limit</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getFindAttr <em>Find Attr</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getApplyManipulation <em>Apply Manipulation</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getOnUpdateKey <em>On Update Key</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getFetchBatchSize <em>Fetch Batch Size</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getWriteBatchSize <em>Write Batch Size</em>}</li>
 *   <li>{@link in.handyman.dsl.Mongo2Db#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see in.handyman.dsl.DslPackage#getMongo2Db()
 * @model
 * @generated
 */
public interface Mongo2Db extends Action
{
  /**
   * Returns the value of the '<em><b>Source Conn Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Conn Str</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Conn Str</em>' attribute.
   * @see #setSourceConnStr(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_SourceConnStr()
   * @model
   * @generated
   */
  String getSourceConnStr();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getSourceConnStr <em>Source Conn Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Conn Str</em>' attribute.
   * @see #getSourceConnStr()
   * @generated
   */
  void setSourceConnStr(String value);

  /**
   * Returns the value of the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' attribute.
   * @see #setTo(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_To()
   * @model
   * @generated
   */
  String getTo();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getTo <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' attribute.
   * @see #getTo()
   * @generated
   */
  void setTo(String value);

  /**
   * Returns the value of the '<em><b>Source Db</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Db</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Db</em>' attribute.
   * @see #setSourceDb(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_SourceDb()
   * @model
   * @generated
   */
  String getSourceDb();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getSourceDb <em>Source Db</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Db</em>' attribute.
   * @see #getSourceDb()
   * @generated
   */
  void setSourceDb(String value);

  /**
   * Returns the value of the '<em><b>Target Db</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Db</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Db</em>' attribute.
   * @see #setTargetDb(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_TargetDb()
   * @model
   * @generated
   */
  String getTargetDb();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getTargetDb <em>Target Db</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Db</em>' attribute.
   * @see #getTargetDb()
   * @generated
   */
  void setTargetDb(String value);

  /**
   * Returns the value of the '<em><b>Target Table</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Table</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Table</em>' attribute.
   * @see #setTargetTable(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_TargetTable()
   * @model
   * @generated
   */
  String getTargetTable();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getTargetTable <em>Target Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Table</em>' attribute.
   * @see #getTargetTable()
   * @generated
   */
  void setTargetTable(String value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filter</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' attribute.
   * @see #setFilter(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_Filter()
   * @model
   * @generated
   */
  String getFilter();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getFilter <em>Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' attribute.
   * @see #getFilter()
   * @generated
   */
  void setFilter(String value);

  /**
   * Returns the value of the '<em><b>Limit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Limit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Limit</em>' attribute.
   * @see #setLimit(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_Limit()
   * @model
   * @generated
   */
  String getLimit();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getLimit <em>Limit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Limit</em>' attribute.
   * @see #getLimit()
   * @generated
   */
  void setLimit(String value);

  /**
   * Returns the value of the '<em><b>Find Attr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Find Attr</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Find Attr</em>' attribute.
   * @see #setFindAttr(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_FindAttr()
   * @model
   * @generated
   */
  String getFindAttr();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getFindAttr <em>Find Attr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Find Attr</em>' attribute.
   * @see #getFindAttr()
   * @generated
   */
  void setFindAttr(String value);

  /**
   * Returns the value of the '<em><b>Apply Manipulation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Apply Manipulation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Apply Manipulation</em>' attribute.
   * @see #setApplyManipulation(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_ApplyManipulation()
   * @model
   * @generated
   */
  String getApplyManipulation();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getApplyManipulation <em>Apply Manipulation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Apply Manipulation</em>' attribute.
   * @see #getApplyManipulation()
   * @generated
   */
  void setApplyManipulation(String value);

  /**
   * Returns the value of the '<em><b>On Update Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>On Update Key</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>On Update Key</em>' attribute.
   * @see #setOnUpdateKey(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_OnUpdateKey()
   * @model
   * @generated
   */
  String getOnUpdateKey();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getOnUpdateKey <em>On Update Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>On Update Key</em>' attribute.
   * @see #getOnUpdateKey()
   * @generated
   */
  void setOnUpdateKey(String value);

  /**
   * Returns the value of the '<em><b>Fetch Batch Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fetch Batch Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fetch Batch Size</em>' attribute.
   * @see #setFetchBatchSize(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_FetchBatchSize()
   * @model
   * @generated
   */
  String getFetchBatchSize();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getFetchBatchSize <em>Fetch Batch Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fetch Batch Size</em>' attribute.
   * @see #getFetchBatchSize()
   * @generated
   */
  void setFetchBatchSize(String value);

  /**
   * Returns the value of the '<em><b>Write Batch Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Write Batch Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write Batch Size</em>' attribute.
   * @see #setWriteBatchSize(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_WriteBatchSize()
   * @model
   * @generated
   */
  String getWriteBatchSize();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getWriteBatchSize <em>Write Batch Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write Batch Size</em>' attribute.
   * @see #getWriteBatchSize()
   * @generated
   */
  void setWriteBatchSize(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see in.handyman.dsl.DslPackage#getMongo2Db_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Mongo2Db#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Mongo2Db
