/**
 * generated by Xtext 2.16.0
 */
package in.handyman.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unzip</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.Unzip#getSource <em>Source</em>}</li>
 *   <li>{@link in.handyman.dsl.Unzip#getDestDir <em>Dest Dir</em>}</li>
 *   <li>{@link in.handyman.dsl.Unzip#getBufferSize <em>Buffer Size</em>}</li>
 *   <li>{@link in.handyman.dsl.Unzip#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see in.handyman.dsl.DslPackage#getUnzip()
 * @model
 * @generated
 */
public interface Unzip extends Action
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(String)
   * @see in.handyman.dsl.DslPackage#getUnzip_Source()
   * @model
   * @generated
   */
  String getSource();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Unzip#getSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #getSource()
   * @generated
   */
  void setSource(String value);

  /**
   * Returns the value of the '<em><b>Dest Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dest Dir</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dest Dir</em>' attribute.
   * @see #setDestDir(String)
   * @see in.handyman.dsl.DslPackage#getUnzip_DestDir()
   * @model
   * @generated
   */
  String getDestDir();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Unzip#getDestDir <em>Dest Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dest Dir</em>' attribute.
   * @see #getDestDir()
   * @generated
   */
  void setDestDir(String value);

  /**
   * Returns the value of the '<em><b>Buffer Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Buffer Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Buffer Size</em>' attribute.
   * @see #setBufferSize(String)
   * @see in.handyman.dsl.DslPackage#getUnzip_BufferSize()
   * @model
   * @generated
   */
  String getBufferSize();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Unzip#getBufferSize <em>Buffer Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Buffer Size</em>' attribute.
   * @see #getBufferSize()
   * @generated
   */
  void setBufferSize(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see in.handyman.dsl.DslPackage#getUnzip_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link in.handyman.dsl.Unzip#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Unzip
