/**
 * generated by Xtext 2.16.0
 */
package in.handyman.dsl.impl;

import in.handyman.dsl.Checksum;
import in.handyman.dsl.DslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Checksum</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.impl.ChecksumImpl#getHost <em>Host</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.ChecksumImpl#getPort <em>Port</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.ChecksumImpl#getUsername <em>Username</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.ChecksumImpl#getPassword <em>Password</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.ChecksumImpl#getLocalDir <em>Local Dir</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.ChecksumImpl#getLocalFile <em>Local File</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.ChecksumImpl#getRemoteDir <em>Remote Dir</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.ChecksumImpl#getRemoteFile <em>Remote File</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.ChecksumImpl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ChecksumImpl extends ActionImpl implements Checksum
{
  /**
   * The default value of the '{@link #getHost() <em>Host</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHost()
   * @generated
   * @ordered
   */
  protected static final String HOST_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHost() <em>Host</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHost()
   * @generated
   * @ordered
   */
  protected String host = HOST_EDEFAULT;

  /**
   * The default value of the '{@link #getPort() <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPort()
   * @generated
   * @ordered
   */
  protected static final String PORT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPort() <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPort()
   * @generated
   * @ordered
   */
  protected String port = PORT_EDEFAULT;

  /**
   * The default value of the '{@link #getUsername() <em>Username</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsername()
   * @generated
   * @ordered
   */
  protected static final String USERNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUsername() <em>Username</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsername()
   * @generated
   * @ordered
   */
  protected String username = USERNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPassword() <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPassword()
   * @generated
   * @ordered
   */
  protected static final String PASSWORD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPassword() <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPassword()
   * @generated
   * @ordered
   */
  protected String password = PASSWORD_EDEFAULT;

  /**
   * The default value of the '{@link #getLocalDir() <em>Local Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocalDir()
   * @generated
   * @ordered
   */
  protected static final String LOCAL_DIR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLocalDir() <em>Local Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocalDir()
   * @generated
   * @ordered
   */
  protected String localDir = LOCAL_DIR_EDEFAULT;

  /**
   * The default value of the '{@link #getLocalFile() <em>Local File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocalFile()
   * @generated
   * @ordered
   */
  protected static final String LOCAL_FILE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLocalFile() <em>Local File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocalFile()
   * @generated
   * @ordered
   */
  protected String localFile = LOCAL_FILE_EDEFAULT;

  /**
   * The default value of the '{@link #getRemoteDir() <em>Remote Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRemoteDir()
   * @generated
   * @ordered
   */
  protected static final String REMOTE_DIR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRemoteDir() <em>Remote Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRemoteDir()
   * @generated
   * @ordered
   */
  protected String remoteDir = REMOTE_DIR_EDEFAULT;

  /**
   * The default value of the '{@link #getRemoteFile() <em>Remote File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRemoteFile()
   * @generated
   * @ordered
   */
  protected static final String REMOTE_FILE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRemoteFile() <em>Remote File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRemoteFile()
   * @generated
   * @ordered
   */
  protected String remoteFile = REMOTE_FILE_EDEFAULT;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChecksumImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.CHECKSUM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getHost()
  {
    return host;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHost(String newHost)
  {
    String oldHost = host;
    host = newHost;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.CHECKSUM__HOST, oldHost, host));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPort()
  {
    return port;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPort(String newPort)
  {
    String oldPort = port;
    port = newPort;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.CHECKSUM__PORT, oldPort, port));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getUsername()
  {
    return username;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUsername(String newUsername)
  {
    String oldUsername = username;
    username = newUsername;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.CHECKSUM__USERNAME, oldUsername, username));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPassword()
  {
    return password;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPassword(String newPassword)
  {
    String oldPassword = password;
    password = newPassword;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.CHECKSUM__PASSWORD, oldPassword, password));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLocalDir()
  {
    return localDir;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLocalDir(String newLocalDir)
  {
    String oldLocalDir = localDir;
    localDir = newLocalDir;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.CHECKSUM__LOCAL_DIR, oldLocalDir, localDir));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLocalFile()
  {
    return localFile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLocalFile(String newLocalFile)
  {
    String oldLocalFile = localFile;
    localFile = newLocalFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.CHECKSUM__LOCAL_FILE, oldLocalFile, localFile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getRemoteDir()
  {
    return remoteDir;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRemoteDir(String newRemoteDir)
  {
    String oldRemoteDir = remoteDir;
    remoteDir = newRemoteDir;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.CHECKSUM__REMOTE_DIR, oldRemoteDir, remoteDir));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getRemoteFile()
  {
    return remoteFile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRemoteFile(String newRemoteFile)
  {
    String oldRemoteFile = remoteFile;
    remoteFile = newRemoteFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.CHECKSUM__REMOTE_FILE, oldRemoteFile, remoteFile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.CHECKSUM__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.CHECKSUM__HOST:
        return getHost();
      case DslPackage.CHECKSUM__PORT:
        return getPort();
      case DslPackage.CHECKSUM__USERNAME:
        return getUsername();
      case DslPackage.CHECKSUM__PASSWORD:
        return getPassword();
      case DslPackage.CHECKSUM__LOCAL_DIR:
        return getLocalDir();
      case DslPackage.CHECKSUM__LOCAL_FILE:
        return getLocalFile();
      case DslPackage.CHECKSUM__REMOTE_DIR:
        return getRemoteDir();
      case DslPackage.CHECKSUM__REMOTE_FILE:
        return getRemoteFile();
      case DslPackage.CHECKSUM__VALUE:
        return getValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.CHECKSUM__HOST:
        setHost((String)newValue);
        return;
      case DslPackage.CHECKSUM__PORT:
        setPort((String)newValue);
        return;
      case DslPackage.CHECKSUM__USERNAME:
        setUsername((String)newValue);
        return;
      case DslPackage.CHECKSUM__PASSWORD:
        setPassword((String)newValue);
        return;
      case DslPackage.CHECKSUM__LOCAL_DIR:
        setLocalDir((String)newValue);
        return;
      case DslPackage.CHECKSUM__LOCAL_FILE:
        setLocalFile((String)newValue);
        return;
      case DslPackage.CHECKSUM__REMOTE_DIR:
        setRemoteDir((String)newValue);
        return;
      case DslPackage.CHECKSUM__REMOTE_FILE:
        setRemoteFile((String)newValue);
        return;
      case DslPackage.CHECKSUM__VALUE:
        setValue((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.CHECKSUM__HOST:
        setHost(HOST_EDEFAULT);
        return;
      case DslPackage.CHECKSUM__PORT:
        setPort(PORT_EDEFAULT);
        return;
      case DslPackage.CHECKSUM__USERNAME:
        setUsername(USERNAME_EDEFAULT);
        return;
      case DslPackage.CHECKSUM__PASSWORD:
        setPassword(PASSWORD_EDEFAULT);
        return;
      case DslPackage.CHECKSUM__LOCAL_DIR:
        setLocalDir(LOCAL_DIR_EDEFAULT);
        return;
      case DslPackage.CHECKSUM__LOCAL_FILE:
        setLocalFile(LOCAL_FILE_EDEFAULT);
        return;
      case DslPackage.CHECKSUM__REMOTE_DIR:
        setRemoteDir(REMOTE_DIR_EDEFAULT);
        return;
      case DslPackage.CHECKSUM__REMOTE_FILE:
        setRemoteFile(REMOTE_FILE_EDEFAULT);
        return;
      case DslPackage.CHECKSUM__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.CHECKSUM__HOST:
        return HOST_EDEFAULT == null ? host != null : !HOST_EDEFAULT.equals(host);
      case DslPackage.CHECKSUM__PORT:
        return PORT_EDEFAULT == null ? port != null : !PORT_EDEFAULT.equals(port);
      case DslPackage.CHECKSUM__USERNAME:
        return USERNAME_EDEFAULT == null ? username != null : !USERNAME_EDEFAULT.equals(username);
      case DslPackage.CHECKSUM__PASSWORD:
        return PASSWORD_EDEFAULT == null ? password != null : !PASSWORD_EDEFAULT.equals(password);
      case DslPackage.CHECKSUM__LOCAL_DIR:
        return LOCAL_DIR_EDEFAULT == null ? localDir != null : !LOCAL_DIR_EDEFAULT.equals(localDir);
      case DslPackage.CHECKSUM__LOCAL_FILE:
        return LOCAL_FILE_EDEFAULT == null ? localFile != null : !LOCAL_FILE_EDEFAULT.equals(localFile);
      case DslPackage.CHECKSUM__REMOTE_DIR:
        return REMOTE_DIR_EDEFAULT == null ? remoteDir != null : !REMOTE_DIR_EDEFAULT.equals(remoteDir);
      case DslPackage.CHECKSUM__REMOTE_FILE:
        return REMOTE_FILE_EDEFAULT == null ? remoteFile != null : !REMOTE_FILE_EDEFAULT.equals(remoteFile);
      case DslPackage.CHECKSUM__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (host: ");
    result.append(host);
    result.append(", port: ");
    result.append(port);
    result.append(", username: ");
    result.append(username);
    result.append(", password: ");
    result.append(password);
    result.append(", localDir: ");
    result.append(localDir);
    result.append(", localFile: ");
    result.append(localFile);
    result.append(", remoteDir: ");
    result.append(remoteDir);
    result.append(", remoteFile: ");
    result.append(remoteFile);
    result.append(", value: ");
    result.append(value);
    result.append(')');
    return result.toString();
  }

} //ChecksumImpl
