/**
 * generated by Xtext 2.16.0
 */
package in.handyman.dsl.impl;

import in.handyman.dsl.DslPackage;
import in.handyman.dsl.Unzip;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Unzip</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link in.handyman.dsl.impl.UnzipImpl#getSource <em>Source</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.UnzipImpl#getDestDir <em>Dest Dir</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.UnzipImpl#getBufferSize <em>Buffer Size</em>}</li>
 *   <li>{@link in.handyman.dsl.impl.UnzipImpl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UnzipImpl extends ActionImpl implements Unzip
{
  /**
   * The default value of the '{@link #getSource() <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSource()
   * @generated
   * @ordered
   */
  protected static final String SOURCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSource() <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSource()
   * @generated
   * @ordered
   */
  protected String source = SOURCE_EDEFAULT;

  /**
   * The default value of the '{@link #getDestDir() <em>Dest Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDestDir()
   * @generated
   * @ordered
   */
  protected static final String DEST_DIR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDestDir() <em>Dest Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDestDir()
   * @generated
   * @ordered
   */
  protected String destDir = DEST_DIR_EDEFAULT;

  /**
   * The default value of the '{@link #getBufferSize() <em>Buffer Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBufferSize()
   * @generated
   * @ordered
   */
  protected static final String BUFFER_SIZE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBufferSize() <em>Buffer Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBufferSize()
   * @generated
   * @ordered
   */
  protected String bufferSize = BUFFER_SIZE_EDEFAULT;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UnzipImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.UNZIP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSource()
  {
    return source;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSource(String newSource)
  {
    String oldSource = source;
    source = newSource;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.UNZIP__SOURCE, oldSource, source));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDestDir()
  {
    return destDir;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDestDir(String newDestDir)
  {
    String oldDestDir = destDir;
    destDir = newDestDir;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.UNZIP__DEST_DIR, oldDestDir, destDir));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getBufferSize()
  {
    return bufferSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBufferSize(String newBufferSize)
  {
    String oldBufferSize = bufferSize;
    bufferSize = newBufferSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.UNZIP__BUFFER_SIZE, oldBufferSize, bufferSize));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.UNZIP__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.UNZIP__SOURCE:
        return getSource();
      case DslPackage.UNZIP__DEST_DIR:
        return getDestDir();
      case DslPackage.UNZIP__BUFFER_SIZE:
        return getBufferSize();
      case DslPackage.UNZIP__VALUE:
        return getValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.UNZIP__SOURCE:
        setSource((String)newValue);
        return;
      case DslPackage.UNZIP__DEST_DIR:
        setDestDir((String)newValue);
        return;
      case DslPackage.UNZIP__BUFFER_SIZE:
        setBufferSize((String)newValue);
        return;
      case DslPackage.UNZIP__VALUE:
        setValue((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.UNZIP__SOURCE:
        setSource(SOURCE_EDEFAULT);
        return;
      case DslPackage.UNZIP__DEST_DIR:
        setDestDir(DEST_DIR_EDEFAULT);
        return;
      case DslPackage.UNZIP__BUFFER_SIZE:
        setBufferSize(BUFFER_SIZE_EDEFAULT);
        return;
      case DslPackage.UNZIP__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.UNZIP__SOURCE:
        return SOURCE_EDEFAULT == null ? source != null : !SOURCE_EDEFAULT.equals(source);
      case DslPackage.UNZIP__DEST_DIR:
        return DEST_DIR_EDEFAULT == null ? destDir != null : !DEST_DIR_EDEFAULT.equals(destDir);
      case DslPackage.UNZIP__BUFFER_SIZE:
        return BUFFER_SIZE_EDEFAULT == null ? bufferSize != null : !BUFFER_SIZE_EDEFAULT.equals(bufferSize);
      case DslPackage.UNZIP__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (source: ");
    result.append(source);
    result.append(", destDir: ");
    result.append(destDir);
    result.append(", bufferSize: ");
    result.append(bufferSize);
    result.append(", value: ");
    result.append(value);
    result.append(')');
    return result.toString();
  }

} //UnzipImpl
